### ISSUE TITLE
Resources used during build process

### ISSUE THREAD

**Issue by creatornader** [Patrik-Stas/indyscan#6]
Thanks for writing this! I am currently experimenting with the code and my computer crashed a few times because I was multitasking while doing so. I ran some tests in isolation and I just wanted to ask you if you are aware how resource-intensive the build command is `./build-all.sh`. I'm running Ubuntu 16.04 with an i5-5300U and it is maxing out all 4 cores of my CPU. Granted its a modest machine but is this behavior expected? Is most of this build process being eaten up by the webapp as opposed to the daemon?

**Comment by creatornader** [comment]
Unrelated but I also noticed the `Structure` overview in the README doesn't quite match with the Github structure. Am I missing something? I can also open a separate issue if you wish.

**Comment by Patrik-Stas** [comment]
Hi @creatornader thanks for insights! 

About the docs:
I was doing some restructuring recently so I've probably forgot to update the readme properly. I widely welcome any PR with improvments and fixes. Otherwise I can fix the readme probably the upcoming weekend.

Resource consumption of `./build-all.sh`:
the reason is because the command builds docker images and they are not small ones. Particularly the base image - ubuntu with libindy, node and rust is probably expensive to build. There's probably space for optimizations building them, but it's not something I am me myself planning to get into soon (PRs are welcome :-) )
However note that the build process is expensive only the 1st time you do it. After you've ran it successfully once, it will be way faster next time you run it (as the base layers of docker images are already built)
A quick remedy I can think of for users who would like to avoid running `./build-all.sh` would be to use docker images I am building for indyscan.io deployments:

https://cloud.docker.com/repository/docker/pstas/indyscan-daemon
https://cloud.docker.com/repository/docker/pstas/indyscan-webapp

But on the other hand, unfortunately right now these images are huge, so it might be a lot of pain to download them if you are on slow connection.

**Comment by Patrik-Stas** [comment]
@creatornader I am writing some automation to startup indyscan along with indypool and giving user option to either automatically download images, or build them locally. Should be complete within few days.

**Comment by creatornader** [comment]
@Patrik-Stas fantastic, looks like some of that logic has already been merged in? correct me if i'm wrong

**Comment by Patrik-Stas** [comment]
Yes, as we've discussed privately it's now merged. As for anyone else looking into this Issue thread, it's possible to decide whether you want to build all images locally or download them from dockerhub when running locally. You can find instructions here https://github.com/Patrik-Stas/indyscan/blob/master/start/README.md#download-or-build-images
